import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class PhotoService {
  private readonly s3Url: string =
    "https://weston-life.s3.amazonaws.com/photos/";
  private readonly photos = {
    arizona: [
      "/grand-canyon-between-tree-branches.jpg",
      "/grand-canyon-castle-and-view-2.jpg",
      "/grand-canyon-castle-and-view.jpg",
      "/grand-canyon-fish-eye-view.jpg",
      "/grand-canyon-rabbit-on-wall.jpg",
      "/grand-canyon-tower-spiral-and-art.jpg",
    ],
    colorado: [
      "/boulder-hike-overview.jpg",
      "/colorado-random-side-road.jpg",
      "/garden-of-the-gods-panorama.jpg",
      "/garden-of-the-gods-trail-bend.jpg",
      "/garden-of-the-gods-trail-cliff-side-mountain-view.jpg",
      "/garden-of-the-gods-trail-close-up-rock-form-and-spores.jpg",
      "/garden-of-the-gods-trail-end.jpg",
      "/garden-of-the-gods-trail-misc-mountains.jpg",
      "/garden-of-the-gods-trail-mountains-behind.jpg",
      "/garden-of-the-gods-trail-pigeons.jpg",
      "/garden-of-the-gods-trail-trail-sunrise.jpg",
      "/manitou-cliff-dwellings-mountain-view-with-gate-thing.jpg",
      "/manitou-cliff-dwellings-mountain-view.jpg",
      "/manitou-spring-metal-sculptures.jpg",
      "/manitou-springs-clif-dwellings-panorama.jpg",
      "/manitou-springs-crafty-twig-roof.jpg",
      "/manitou-springs-creatures.jpg",
      "/manitou-springs-hut-house.jpg",
      "/manitou-springs-metal-dinosaur-sculptures.jpg",
      "/manitou-springs-midway-stairs-treading-it.jpg",
      "/manitou-springs-side-steps-mountains.jpg",
      "/manitou-springs-stairs-and-mountains-looking-out.jpg",
      "/manitou-springs-start-look-behind.jpg",
      "/manitou-springs-starter-stairs.jpg",
      "/manitou-springs-tower.jpg",
      "/manitou-springs-water-guard.jpg",
      "/manitou-springs-within-the-cliff-dwellings.jpg",
      "/national-sand-dunes-bird-and-mountain-view.jpg",
      "/national-sand-dunes-close-up-with-dunes.jpg",
      "/national-sand-dunes-far-away-view-and-mountains.jpg",
      "/national-sand-dunes-looking-down.jpg",
      "/national-sand-dunes-mountain-side.jpg",
      "/national-sand-dunes-mountain-view-epic.jpg",
      "/national-sand-dunes-shoes-filled.jpg",
      "/national-sand-dunes-side-dunes-look.jpg",
      "/national-sand-dunes-side-epic-view-frozen.jpg",
      "/national-sand-dunes-steps-and-mountains.jpg",
      "/national-sand-dunes-surrounding-mountains.jpg",
      "/national-sand-dunes-thistle-and-mountain.jpg",
      "/national-sand-dunes-way-back-with-tree.jpg",
      "/red-rock-bush-and-stone.jpg",
      "/red-rock-castle-mountain.jpg",
      "/red-rock-epic-frozen-lake-and-rocks.jpg",
      "/red-rock-epic-panorama.jpg",
      "/red-rock-epic-stone-in-ice.jpg",
      "/red-rock-epic-valley.jpg",
      "/red-rock-epic-walkway-with-tree-and-massive-steps.jpg",
      "/red-rock-epic-walkway.jpg",
      "/red-rock-etched-in-steps.jpg",
      "/red-rock-field-with-things-in-background.jpg",
      "/red-rock-frozen-closer-up-overview.jpg",
      "/red-rock-frozen-lake-from-afar.jpg",
      "/red-rock-frozen-lake-tree-reaching-over.jpg",
      "/red-rock-mountain-and-field-epic.jpg",
      "/red-rock-mountain-side-field-view.jpg",
      "/red-rock-mountain-side-frozen-lake-view.jpg",
      "/red-rock-mountain-view.jpg",
      "/red-rock-nearly-there-steps.jpg",
      "/red-rock-on-the-frozen-lake.jpg",
      "/red-rock-pathway-panorama.jpg",
      "/red-rock-prickly-bush.jpg",
      "/red-rock-random-entry-trail.jpg",
      "/red-rock-random-peak.jpg",
      "/red-rock-round-the-bend-steps.jpg",
      "/red-rock-side-shoots.jpg",
      "/red-rock-simba-tree.jpg",
      "/red-rock-stone-path-side-mountain.jpg",
      "/red-rock-weeds-and-frozen-lake.jpg",
      "/red-rocks-field-and-mountain.jpg",
    ],
    "new-mexico": [
      "/carlsbad-caverns-all-the-spikes.jpg",
      "/carlsbad-caverns-dolls-theater.jpg",
      "/carlsbad-caverns-drips.jpg",
      "/carlsbad-caverns-entrance-descent.jpg",
      "/carlsbad-caverns-entrance.jpg",
      "/carlsbad-caverns-fairyland.jpg",
      "/carlsbad-caverns-flooded-remains.jpg",
      "/carlsbad-caverns-loop-panorama.jpg",
      "/carlsbad-caverns-more-teeth.jpg",
      "/carlsbad-caverns-reflection-pond.jpg",
      "/carlsbad-caverns-towers.jpg",
      "/carlsbad-caverns-white-top-spikes.jpg",
      "/white-sand-dunes-and-the-shadowy-sticks.jpg",
      "/white-sand-dunes-calling-it-a-meteor.jpg",
      "/white-sand-dunes-meteor-up-close.jpg",
      "/white-sand-dunes-mountain-view.jpg",
      "/white-sand-dunes-panorama.jpg",
      "/white-sand-dunes-tracks.jpg",
      "/white-sand-dunes-valley.jpg",
    ],
    utah: [
      "/angels-landing-bottom-view-panorama.jpg",
      "/angels-landing-canyon-river-view.jpg",
      "/angels-landing-canyons.jpg",
      "/angels-landing-fallen-tree-view.jpg",
      "/angels-landing-looking-back-view.jpg",
      "/angels-landing-panorama-side-view.jpg",
      "/angels-landing-random-cliff.jpg",
      "/angels-landing-side-river-winding-view.jpg",
      "/angels-landing-starting-side-mountain.jpg",
      "/angels-landing-top-rock-pile.jpg",
      "/angels-landing-walk-up-view.jpg",
      "/angels-landing-white-orange.jpg",
    ],
  };
  public getPhotosFromCategory(category: string): string[] {
    return this.photos[category]
      .slice()
      .map((photo) => (photo = this.s3Url + category + photo));
  }
}
